<?php

require 'includes/hardwoods_help.node.form.php';

/**
 * Define a new content type.
 *
 * @implements hook_node_info()
 *
 * @return array
 */
function hardwoods_help_node_info() {
  return [
    'help' => [
      'name' => t('Help Page'),
      'description' => t('Create a tabbed help page'),
      'base' => 'hardwoods_help',
      'has_title' => TRUE,
      'title_label' => t('Page Title'),
    ],
  ];
}

/**
 * Implements hook_node_view().
 */
function hardwoods_help_node_view($node, $view_mode, $langcode) {

}

/**
 * Implements hook_theme().
 */
function hardwoods_help_theme($existing, $type, $theme, $path) {
  return [];
}