<?php

require 'includes/hardwoods_help.node.form.php';
require 'api/hardwoods_help.api.php';

/**
 * Define a new content type.
 *
 * @implements hook_node_info()
 *
 * @return array
 */
function hardwoods_help_node_info() {
  return [
    'help' => [
      'name' => t('Help Page'),
      'description' => t('Create a tabbed help page'),
      'base' => 'hardwoods_help',
      'has_title' => TRUE,
      'title_label' => t('Page Title'),
    ],
  ];
}

/**
 * Implements hook_node_view().
 *
 * @throws \Exception
 */
function hardwoods_help_node_view($node, $view_mode, $langcode) {
  if ($node->type === 'help') {
    // Load the fields
    $fields = hardwoods_help_get_fields($node->nid);

    if ($view_mode === 'full') {
      $node->content['help-content'] = [
        '#type' => 'markup',
        '#markup' => theme('node-help', [
          'node' => $node,
          'fields' => $fields,
        ]),
      ];
    }
    else {
      $content = [];
      foreach ($fields as $field) {
        $content[] = $field->title;
      }

      $node->content['help-content'] = [
        '#type' => 'markup',
        '#markup' => implode('<br />', $content),
      ];
    }
  }
}

/**
 * Implements hook_theme().
 */
function hardwoods_help_theme($existing, $type, $theme, $path) {
  return [
    'node-help' => [
      'arguments' => [
        'node' => NULL,
        'fields' => NULL,
      ],
      'template' => 'node--help',
      'path' => "$path/theme/templates",
    ],
    'help-page-index' => [
      'arguments' => [
        'items'
      ],
      'template' => 'help_page_index',
      'path' => "$path/theme/templates",
    ],
  ];
}

/**
 * Implements hook_node_delete().
 *
 * Delete the fields associated with the node.
 */
function hardwoods_help_node_delete($node) {
  db_query("DELETE FROM {hardwoods_help} WHERE nid = :nid", [
    ':nid' => $node->nid,
  ]);
}

/**
 * Implements hook_block_info().
 */
function hardwoods_help_block_info() {
  $block = [];

  $block['help_index_block'] = [
    'info' => t('Index of Help Pages and Topics'),
    'cache' => DRUPAL_NO_CACHE
  ];

  return $block;
}

/**
 * Implements hook_block_view().
 *
 * @throws \Exception;
 *
 * @return mixed|null
 */
function hardwoods_help_block_view($delta = '') {
  if($delta !== 'help_index_block') {
    return null;
  }

  return theme('help-page-index', [
    'items' => hardwoods_help_get_help_menu_items()
  ]);
}
