<?php

require 'includes/hardwoods_help.node.form.php';
require 'api/hardwoods_help.api.php';

/**
 * Define a new content type.
 *
 * @implements hook_node_info()
 *
 * @return array
 */
function hardwoods_help_node_info() {
  return [
    'help' => [
      'name' => t('Help Page'),
      'description' => t('Create a tabbed help page'),
      'base' => 'hardwoods_help',
      'has_title' => TRUE,
      'title_label' => t('Page Title'),
    ],
  ];
}

/**
 * Implements hook_node_view().
 */
function hardwoods_help_node_view($node, $view_mode, $langcode) {
  if ($view_mode === 'full' && $node->type === 'help') {
    // Load the fields
    $fields = hardwoods_help_get_fields($node->nid);

    $node->content['help-content'] = [
      '#type' => 'markup',
      '#markup' => theme('node-help', [
        'node' => $node,
        'fields' => $fields,
      ]),
    ];
  }
}

/**
 * Implements hook_theme().
 */
function hardwoods_help_theme($existing, $type, $theme, $path) {
  return [
    'node-help' => [
      'arguments' => [
        'node' => NULL,
        'fields' => NULL,
      ],
      'template' => 'node--help',
      'path' => "$path/theme/templates",
    ],
  ];
}

/**
 * Implements hook_node_delete().
 */
function hardwoods_help_node_delete($node) {
  db_query("DELETE FROM {hardwoods_help} WHERE nid = :nid", [
    ':nid' => $node->nid,
  ]);
}